### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by robj411** [metahit/mh-execute#1]
Here is what needs to be done to get Metahit to the same stage as ITHIM-R:

- [ ] put in correct GBD data: mh-execute/inputs/gbd
- [ ] put in correct population data: mh-execute/inputs/populations
- [ ] put in correct AP data: mh-execute/inputs/background-air-pollution/1_apmeans.csv
- [ ] generalise to multiple scenarios
- [ ] sort out/harmonise naming conventions, including: modes, scenarios, city regions
- [ ] include tube and rail in distances - they should be in inh_distances (see mh-distances/process_distances_for_execute.R)
- [ ] set other AP parameters - transport fraction of AP and source apportionment
- [ ] check MMET distributions and computation if it doesn't look right
- [ ] calculate pm inhalation (inh_distances) as durations. needs allocation by road and la (if the module is to compute exposure by road and la). can be done in mh-distances/process_distances_for_execute.R or via speeds.
- [ ] check that nottingham is working
- [ ] delete pa_distances from mh-distances/process_distances_for_execute.R and compute pa by summing over inh

To get to Metahit:
- [ ] change AP exposure computation, if it is to be by road and la
- [ ] noise pathway
- [ ] no2 pathway
- [ ] re-arrange or recode set_ithim_parameters so that they can all be set in advance of the city loop. this means that e.g. PM_CONC_BASE is a standard normal and the cities scale values according to their means and SDs.

**Comment by AnnaGoodman1** [comment]
Thanks v muvh @robj411 . Not clear to me if any are actions for me - do you have an idea who you are assigning to each?

**Comment by robj411** [comment]
There are some points we can discuss at the next meeting, e.g. whether we want to get to the ITHIM-R stage (which would involve sorting out the populations and GBD data) or if we want to skip straight to the MSLT (in which case we can leave those two points out).

You and I could figure out the durations by mode by road type by LA for the inhalation calculation.

We can decide what are priority things for me to finish, and then what remains is just a note of what still needs to be done. Many of these are in metahit_script.R, and there are comments in there for each 'to do' point.

**Comment by AnnaGoodman1** [comment]
great plan
